export const foodData = [
  {
    id: 0,
    name: 'Kibble',
    measure: '1/2 cup',
    desc: 'Purina Large Breed Adult Formula',
    foodCalories: 161,
    qty: 1,
  },
  {
    id: 1,
    name: 'Chicken',
    measure: '1/2 cup',
    desc: 'Skinless, Boneless Chicken Breast',
    foodCalories: 115.5,
    qty: 1,
  },
  {
    id: 2,
    name: 'Egg',
    desc: 'Farm Fresh Large Egg',
    foodCalories: 72,
    qty: 1,
  },
  {
    id: 3,
    name: '1/2 Tomato',
    desc: 'Price Chopper Tennis Ball Size Tomato',
    foodCalories: 11,
    qty: 1,
  },
  {
    id: 4,
    name: 'Salmon Oil',
    measure: '1 Pump',
    desc: 'Grizzly Omega Health Wild Salmon/Pollock Oil',
    foodCalories: 30,
    qty: 1,
  },
  {
    id: 5,
    name: 'Sardines',
    measure: '1 Can',
    desc: 'Season Brand Sardines in Water, No Salt Added',
    foodCalories: 170,
    qty: 1,
  },
  {
    id: 6,
    name: 'Beef Jerky',
    measure: '3 Pcs',
    desc: 'Home Made Top Round London Broil Jerky - Fat Removed',
    foodCalories: 116,
    qty: 1,
  },
  {
    id: 7,
    name: 'Brown Biscuit Treats',
    desc: 'Wholesome Rewards Smoky Bites Biscuit',
    foodCalories: 33,
    qty: 1,
  },
  {
    id: 8,
    name: 'PB Biscuit Treat',
    desc: 'Old Mother Hubbard Classic Natural P-Nutty Biscuit',
    foodCalories: 17,
    qty: 1,
  },
  {
    id: 9,
    name: 'Blue Buffalo Bits Treats',
    desc: 'Blue Buffalo Bits Soft Moist Dog Training Treats',
    foodCalories: 4,
    qty: 1,
  },
];
